name: docker-build

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches-ignore:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  docker:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: geokrety/bootstrap-email
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerfile: Dockerfile
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  update-version-set:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/version-set.yml@main
    needs: docker
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
