name: Semantic release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      # setting up Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      # disable package-lock.json to stop it being created
      - name: Disable package-lock.json
        run: npm config set package-lock false

      # Installing package dependencies
      - name: Install dependencies
        run: |
          npm i -D js-yaml@4.1.0 conventional-changelog-conventionalcommits semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @semantic-release/changelog @semantic-release/github

      - name: New tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: geokrety-bot
          GIT_AUTHOR_EMAIL: geokrety-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: geokrety-bot
          GIT_COMMITTER_EMAIL: geokrety-bot@users.noreply.github.com
        run: npx semantic-release
