name: Update version-set

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  update-version-set:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/version-set.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
